### ISSUE TITLE
Differentiate between error and 0 found password breaches

### ISSUE THREAD

**Issue by davidkassa** [VisualBean/HIBP.NET#1]
Looking at the code, it appears that both an unsuccessful request and an uncompromised password will return a 0 count. Consider returning a -1 or throwing an error if there is an error.

**Comment by VisualBean** [comment]
The API has a few basic statuscodes, which are covered in the [BaseApi](https://github.com/VisualBean/HIBP.NET/blob/df99e626dfe1e8bb84090099b0a55efe4249258d/HIBP.NET/Apis/BaseApi.cs#L63)
429 and 403, the other case which would be 400, is covered by the null check in the beginning of the IsPasswordPwnedAsync method
.
Under no circumstance will that api return 404 (according to the docs).

In any case, the lib will throw if there is a connection problem :).
